server {
  listen 80;
  # DNS Docker: nginx не падает при старте, если backend ещё не поднялся
  resolver 127.0.0.11 ipv6=off valid=10s;

  # Запросы по адресам /api/... перенаправляй в контейнер backend
  location /api/ {
    set $backend backend:8000;
    proxy_set_header Host $http_host;
    proxy_pass http://$backend$request_uri;
  }
  location /admin/ {
    set $backend backend:8000;
    proxy_set_header Host $http_host;
    proxy_pass http://$backend$request_uri;
  }

  location / {
    alias /staticfiles/;
    index index.html;
  }
}
